### ISSUE TITLE
I don't like the new interface at all

### ISSUE THREAD

**Issue by perrohunter** [octatone/reddit.tv#1]
the old interface on reddit.tv was nicer and much cleaner, you should consider bringing it back

**Comment by octatone** [comment]
Not going to clone someone else's work.  The old reddit.tv was designed and built by someone else in php who didn't maintain it.  This version is completely new code, static, lightweight HTML5 + JavaScript.

What about the current interface don't you like?

**Comment by fagga** [comment]
We already discussed this via email, but I’ll repeat for the record (maybe perrohunter agrees with some of my points):

The old CSS was nicer; e.g. the blue shadow in the dark theme looks odd, and the embossed look of the buttons isn’t what modern sites use.

The title of the current video cannot be read completely if too long, unless the mouse is moved over it, which is awkward when leaning back and watching TV. Having the full title besides the video was more comfortable.

The options at the top & the PREV and NEXT buttons should be made more like icons and buttons, not like text links. Not quite sure what to do with the checkboxes.

A missing feature is the navigational list of videos in the current channel. This is very useful to know how much videos are left, to jump to the video you watched a few minutes back, etc. Basicly a form of orientation.

But enough with the criticism. The new implementation is awesome. It runs completely in the browser without the need for a server (thanks to JavaScript and GitHub). It’s very usable (I use it every day) and the new “sfw”, “fill screen” and  “autoadvance” features were missing in the old interface, along with the keybindings. I really missed reddit.tv; thank you for bringing it back.

**Comment by octatone** [comment]
The old style navigation list is going to be troublesome (if not impossible) to implement, because of all the new embed.ly content reddit.com is currently using.  It's not as simple as just loading thumbnails from youtube to slide through, there's much more content available on the new reddit.tv from vimeo, comedy central, abc, etc. (take a peak at tv.js to see the full list of video domains).

It wouldn't be hard, however, to add some status information below the video navigation or to the side e.g. 4 of 20.  Maybe what I'll do for the titles that would get cut off, is to put those, and only those, unclipped into a right sidebar.

Anyway, fagga,  we're digressing from the original issue of a few people not liking the current CSS.  Until I see significant number of complaints (more than two), there is no reason to push forward in changing the current look.

**Comment by fagga** [comment]
I didn’t want to harp on that I don’t like the looks. Sorry if it seemed like that. It’s your project, it works great and colors or other minor unpleasantries won’t stop me from using it. I just wanted to contribute my view to the topic, and I’m completely fine with being the only one supporting it.
