### ISSUE TITLE
Turn video title into link to video site

### ISSUE THREAD

**Issue by fagga** [octatone/reddit.tv#3]
Turning the title of the currently played video into the link to youtube, for example, instead of reddit, would spare me one step in getting that link to show the video to somebody else. This would lighten the load on reddit a tiny bit.

Also, the link to reddit is already available below the video, so this wouldn’t take anything away.

If you give me the okay, I will write a patch.

**Comment by octatone** [comment]
Actually, I'm working on making it so that you can link directly to reddit.tv/#/r/section/id as permalinks to any video.

The only reason why the lower info is a link to reddit is because the vote buttons aren't working 100%.  If you want to get the youtube URL, all you have to do is click on the video while it's playing and it will pop up the video on youtube.com.

Also, if reddit is down, reddit.tv is down as it relies on live feeds from reddit.com.

**Comment by octatone** [comment]
You can also get the share link for most of the embeds, from the embedded player for 99% of the videos, including youtube videos (click the up arrow next to the full screen icon in the youtube player)

**Comment by fagga** [comment]
Permalinks are great. I missed them, too, and they would solve the issue mostly, but...

> The only reason why the lower info is a link to reddit is because the vote buttons aren't working 100%.

The vote buttons have a link to the reddit page, too, don’t they? If I remember correctly, it’s the alien’s head.

> If you want to get the youtube URL, all you have to do is click on the video while it's playing and it will pop up the video on youtube.com.

That opens the youtube page in the same tab reddit.tv is in. Currently, that would kill my list of already played videos and I would have to click on NEXT many times until I get back to where I came from.
Also, I might not want to open the youtube page, just rightclick and get the link.

> Also, if reddit is down, reddit.tv is down as it relies on live feeds from reddit.com.

Not if reddit.tv is already playing while reddit.com goes down.
Also, like today, reddit.com might be just under heavy load and the feeds still get through somehow. It’s just my experience, but the feeds seem to have a higher priority or put less load to the servers than the HTML interface.

> You can also get the share link for most of the embeds, from the embedded player for 99% of the videos

Copy & paste doesn’t work for me with Flash.

So the only reason to have redundant links is that, when the ampersand bug will some day be solved, the link to the comments on reddit will be a tiny alien head instead of the video title. If that is not visible enough, there could be a “42 comments” link added after the voting iframe.

For me, this issue isn’t solved. And you didn’t provide a good reason to outright refuse my suggestion.

**Comment by octatone** [comment]
You are welcome to your opinion, but I would simply prefer the title to remain as a link to reddit.com as it provides an easy means for people to discuss the video and read comments.  I appreciate your help, but just because you suggest something doesn't mean I will like the suggestion or want it implemented.

How about a compromise, what if there was an icon in front of , or below the title to link out to the video source?  Or in small text below the title "[source]" that linked out to the video source?

**Comment by fagga** [comment]
The title area shouldn’t be hacked into pieces that lead to different places. At least, I cannot think of a way to implement that in a non-confusing way.

How about another link at the bottom? Something like “[x] votes - [y] comments - source”. “[x] votes” shouldn’t be a link, then, “[y] comments” would be linking to reddit, and “source” would link to youtube. Something like that.

Actually, I think I like the idea of not putting the direct link into the title but somewhere less highlighted even better. Maybe it could even put the domain or name of the source in the link title. I don’t have a tangible idea at the moment, but something like that.

**Comment by octatone** [comment]
That sounds like a good compromise.

Maybe [x] votes - [y] comments - [domain](links to the source)

Although some of the domains are a bit long, maybe below the comments and votes.
