### ISSUE TITLE
Title should be smaller font

### ISSUE THREAD

**Issue by RedditTVviewer** [octatone/reddit.tv#9]
Reddit title is almost always longer than the space it's given. Solve this by making the font smaller, or enabling word-wrap.

**Comment by octatone** [comment]
reddit title's can be very very long and word wrap would cause the title section area to grow and expand randomly. The full title is available by mousing over the shortened title above the video and by mousing over the tumbnail.  In opera, chrome and safari the title is ended with ellipses for a consistent look.  Firefox as usual, is slow in adopting standards.

**Comment by fagga** [comment]
I, too, think this is an issue. It’s not like there isn’t enough space to display the full title, so, in my opinion, it shouldn’t be shortened at all.

Another way to solve this would be to put the title besides the video. I found this more convenient with the old reddit.tv, and the title could be arbitrarily long.

If the title must be above the video, maybe it could get several lines instead of just one? This wouldn’t be possible with the ellipsis, I guess, but three dots aren’t adding much anyway, compared to a complete title.

**Comment by octatone** [comment]
I will not push a solution that results in the title displayed on the side.  It widens the layout and is not "tight" design.  I'll play around with including the full title above the video, but if it is visually distracting or breaks the layout I am not going to push it.  Fagga, don't send me any patches regarding this as I am actively working on it.

**Comment by fagga** [comment]
To me, the old reddit.tv was just as tight as the current one. But it’s your call, I’m just saying what I think.

And don’t worry, I won’t make any big layout/color changes again without asking you first. (:

**Comment by octatone** [comment]
Played around with the title display and with a small enough font it doess't look so bad when the title div expands.  Code pushed.

**Comment by fagga** [comment]
That’s much better. Thanks for fixing!

**Comment by Roach** [comment]
Closed?

**Comment by octatone** [comment]
Ha, yeah :P
